let mySprite: Sprite = null
senseisBlocks.onLeftClick(function (x, y) {
    if (!(senseisBlocks.isGamePaused())) {
        mySprite = senseisBlocks.createScaledSprite(img`
            ...........cccccc...........................
            ..........ccbbbbcc..........................
            .........ccbbbbbbcc.........................
            .........cbbbbbbbbc.........................
            .........cddddddddc.........................
            .........cddddddddc.........................
            .........cdbbdddddc..ccc....................
            .........cddddbbddcccbbcc...................
            .........cddddddddccccbbcc..................
            .........cdbbdddddcccccbddc.................
            .........cddddbbddccccccddc.................
            ...cccccccddddddddcdddddddc.................
            ..ccccccccddddbbddcdddddddc.................
            .cccccccccddddddddbddbdbddcccc..............
            ccccccccccdbbdbbddbddbdbddbcccc.............
            bddddddddcddddddddbdddddddbccccc............
            bddddddddcdbbdbbddbddddbddbccbbc............
            bdbbdbbddcddddddddbddbdbdddcbbbb............
            bddddddddcddddbbddbddddddbdcbbbcc...........
            bdddddddccdbbddddcbddbdddbdbbcccc...........
            bdbbdddccdddddddcccbdbdbdccccccc...cc.......
            bddddddcdddddddcccccdddcc555555cccccc.......
            bddddbbbdddbbdbbdddbbdc5555555555bcc........
            bbcccbbbddddddbdddddbc555555555555b..cc.....
            bccbccbbdddbbdbdbdbdc555551ff555555bccc.....
            ccbbbccbddddddbdddddc55d55ff55555555bcc.....
            cbbbbbbbddddddbdbdbdc5555555555555555b......
            cbbbbbbddddbbdbdddddbcbb31bb55555d555b..c...
            cbbbbbbdddddddbdbdbdbc5333bb55ddddd55dccc...
            bbbbbbbdddddddbdddddbc533b55ddddddddddbc....
            bbbbbbbdddddddbdddddbc5555ddddb55bdddddccc..
            ......................ccccbbbb555bdddddccc..
            .......................cdcbc5555bddddddcc...
            ........................ccbc55bcdddddddbcccc
            .........................cbbccbd55dddddddddc
            .........................ccbbbd555ddddddddbc
            .......................ccbdcbb555ddbbdddbcc.
            .......................cbdddcc55ddbbbbccc...
            .......................cccccccbdddbccc......
            ............................cd555ddc........
            `, SpriteKind.Player)
        mySprite.setPosition(x, y)
        mySprite.lifespan = 5000
        info.changeScoreBy(1)
    }
})
sprites.onDestroyed(SpriteKind.Player, function (sprite) {
    info.changeScoreBy(-1)
})